export const DEFAULT_USERS = [
  {
    id: "usr_admin_1",
    name: "Admin SweetLayers",
    email: "admin@sweetlayers.com",
    phone: "081234567890",
    passwordHash: "02f34e4e6b5351afc6ab1163a31aca891937556501c12323ff77d72dbe537543", // AdminSweetLayers2026!
    role: "admin",
    createdAt: 1726500000000,
  },
];

export const DEFAULT_CATEGORIES = [
  { id: "cat_all", name: "Semua Menu", slug: "all", icon: "🍰" },
  { id: "cat_choco", name: "Choco Lovers", slug: "choco-lovers", icon: "🍫" },
  { id: "cat_cheese", name: "Cheese & Creamy", slug: "cheese-creamy", icon: "🧀" },
  { id: "cat_coffee", name: "Coffee & Tiramisu", slug: "coffee-tiramisu", icon: "☕" },
  { id: "cat_fruity", name: "Fruity Fresh", slug: "fruity-fresh", icon: "🍓" },
  { id: "cat_hampers", name: "Hampers & Bundling", slug: "hampers-bundling", icon: "🎁" },
];

export const DEFAULT_PRODUCTS = [
  {
    id: "p1",
    categoryId: "cat_choco",
    name: "Belgian Dark Choco Melt Box",
    slug: "belgian-dark-choco-melt",
    description: "Lapisan sponge cake cokelat lembut berpadu dengan chocolate mousse premium asal Belgia, ganache dark chocolate leleh, dan taburan choco chips krispi. Rasa cokelat kaya dan tidak bikin enek!",
    shortDesc: "Dark chocolate mousse Belgia dengan melted ganache",
    basePrice: 48000,
    originalPrice: 58000,
    imageUrl: "/images/products/belgian-dark-choco.jpg",
    badge: "Best Seller 🔥",
    temperatureInfo: "Simpan chiller (suhu 2-6°C). Tahan 4-5 hari.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p2",
    categoryId: "cat_coffee",
    name: "Classic Venetian Tiramisu Box",
    slug: "classic-venetian-tiramisu",
    description: "Tiramisu otentik dengan ladyfingers yang dicelupkan ke dalam single-origin espresso aromatik, dilapisi krim keju mascarpone lembut dan taburan bubuk kakao murni tanpa pemanis berlebih.",
    shortDesc: "Espresso dipped ladyfingers & mascarpone cheese lembut",
    basePrice: 52000,
    originalPrice: 62000,
    imageUrl: "/images/products/classic-venetian-tiramisu.jpg",
    badge: "Chef Choice ⭐",
    temperatureInfo: "Simpan chiller. Nikmati selagi dingin untuk sensasi melt-in-mouth.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p3",
    categoryId: "cat_cheese",
    name: "Lotus Biscoff Caramel Velvet",
    slug: "lotus-biscoff-caramel-velvet",
    description: "Perpaduan biskuit Lotus Biscoff renyah di dasar box, disiram cream cheese mousse vanilla, saus selai Biscoff karamel lumer, dan topping biskuit utuh di atasnya.",
    shortDesc: "Cream cheese lembut dipadu lelehan spread Lotus Biscoff",
    basePrice: 49000,
    originalPrice: 55000,
    imageUrl: "/images/products/lotus-biscoff-caramel-velvet.jpg",
    badge: "Favorit 💖",
    temperatureInfo: "Tahan 5 hari dalam kulkas, 2 minggu dalam freezer.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p4",
    categoryId: "cat_cheese",
    name: "Matcha Basque Cream Cheese",
    slug: "matcha-basque-cream-cheese",
    description: "Menggunakan bubuk Uji Matcha asli Jepang dengan aftertaste umami yang khas, dipadukan keju basque yang dipanggang sempurna dengan tekstur tengah yang lembut meleleh.",
    shortDesc: "Uji Matcha autentik berpadu keju bakar creamy",
    basePrice: 54000,
    originalPrice: null,
    imageUrl: "/images/products/matcha-basque-cream-cheese.jpg",
    badge: "Signature 🍵",
    temperatureInfo: "Sajikan dingin langsung dari kulkas.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p5",
    categoryId: "cat_fruity",
    name: "Fresh Strawberry Shortcake Box",
    slug: "fresh-strawberry-shortcake",
    description: "Vanilla sponge selembut awan dilapisi chantilly cream ringan dan potongan buah stroberi segar lokal yang manis-segar, dihiasi selai stroberi buatan dapur kami sendiri.",
    shortDesc: "Potongan stroberi segar & fresh vanilla chantilly cream",
    basePrice: 46000,
    originalPrice: 52000,
    imageUrl: "/images/products/fresh-strawberry-shortcake.jpg",
    badge: "Segar & Manis 🍓",
    temperatureInfo: "Sangat disarankan langsung dihabiskan dalam 2 hari.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p6",
    categoryId: "cat_fruity",
    name: "Mango Coconut Sago Jar",
    slug: "mango-coconut-sago-jar",
    description: "Dessert jar menyegarkan dengan lapisan puree mangga harum manis asli, sagu mutiara lembut, santan kelapa creamy, dan nata de coco kenyal di dalam jar kaca cantik.",
    shortDesc: "Puree mangga manis harum dengan mutiara sagu & kelapa",
    basePrice: 38000,
    originalPrice: null,
    imageUrl: "/images/products/mango-coconut-sago.jpg",
    badge: "Refreshing 🥭",
    temperatureInfo: "Kocok perlahan sebelum dinikmati dingin.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p7",
    categoryId: "cat_cheese",
    name: "Red Velvet Dream Cheese Box",
    slug: "red-velvet-dream-cheese",
    description: "Kue Red Velvet lembab bertabur red velvet crumbs renyah, berpadu dengan frosting cream cheese asam-manis segar yang pas di lidah.",
    shortDesc: "Moist red velvet cake dengan frosting cream cheese segar",
    basePrice: 47000,
    originalPrice: null,
    imageUrl: "/images/products/red-velvet-dream-cheese.jpg",
    badge: "Classic 🍰",
    temperatureInfo: "Tahan 4 hari di chiller.",
    isActive: 1,
    createdAt: 1726500000000,
  },
  {
    id: "p8",
    categoryId: "cat_hampers",
    name: "Grand Festive Hamper (Isi 4 Box)",
    slug: "grand-festive-hamper-4-box",
    description: "Paket hampers eksklusif berisi 4 dessert box favorit (Belgian Choco, Tiramisu, Biscoff, dan Red Velvet), dikemas dengan Hardbox mewah, pita satin, sendok kayu, lilin, dan kartu ucapan kustom.",
    shortDesc: "Paket 4 box terfavorit + Box Mewah + Kartu Ucapan",
    basePrice: 185000,
    originalPrice: 215000,
    imageUrl: "/images/products/grand-festive-hamper.jpg",
    badge: "Diskon Bundling 🎁",
    temperatureInfo: "Bisa pilih pengiriman instan untuk hadiah ulang tahun/kejutan.",
    isActive: 1,
    createdAt: 1726500000000,
  },
];

export const DEFAULT_VARIANTS = [
  { id: "v1_1", productId: "p1", variantName: "Personal Box (350ml)", additionalPrice: 0, stock: 15, sku: "DB-CHOCO-350" },
  { id: "v1_2", productId: "p1", variantName: "Sharing Family Box (500ml)", additionalPrice: 20000, stock: 8, sku: "DB-CHOCO-500" },
  { id: "v2_1", productId: "p2", variantName: "Personal Box (350ml)", additionalPrice: 0, stock: 12, sku: "DB-TIRA-350" },
  { id: "v2_2", productId: "p2", variantName: "Dessert Jar Kaca (250ml)", additionalPrice: -10000, stock: 8, sku: "DB-TIRA-JAR" },
  { id: "v3_1", productId: "p3", variantName: "Personal Box (350ml)", additionalPrice: 0, stock: 14, sku: "DB-BISC-350" },
  { id: "v3_2", productId: "p3", variantName: "Sharing Family Box (500ml)", additionalPrice: 22000, stock: 5, sku: "DB-BISC-500" },
  { id: "v4_1", productId: "p4", variantName: "Personal Box (350ml)", additionalPrice: 0, stock: 9, sku: "DB-MATCHA-350" },
  { id: "v4_2", productId: "p4", variantName: "Mini Cup Bento (200ml)", additionalPrice: -14000, stock: 16, sku: "DB-MATCHA-200" },
  { id: "v5_1", productId: "p5", variantName: "Personal Box (350ml)", additionalPrice: 0, stock: 4, sku: "DB-STRAW-350" },
  { id: "v5_2", productId: "p5", variantName: "Sharing Family Box (500ml)", additionalPrice: 20000, stock: 0, sku: "DB-STRAW-500" },
  { id: "v6_1", productId: "p6", variantName: "Single Glass Jar (300ml)", additionalPrice: 0, stock: 18, sku: "DB-MANGO-300" },
  { id: "v6_2", productId: "p6", variantName: "Twin Jar Duo (2 x 300ml)", additionalPrice: 32000, stock: 8, sku: "DB-MANGO-DUO" },
  { id: "v7_1", productId: "p7", variantName: "Personal Box (350ml)", additionalPrice: 0, stock: 12, sku: "DB-REDV-350" },
  { id: "v7_2", productId: "p7", variantName: "Sharing Family Box (500ml)", additionalPrice: 20000, stock: 6, sku: "DB-REDV-500" },
  { id: "v8_1", productId: "p8", variantName: "Standard Hamper Box + Pita", additionalPrice: 0, stock: 7, sku: "DB-HAMP-STD" },
  { id: "v8_2", productId: "p8", variantName: "Deluxe Hamper + Lilin & Akrilik Topper", additionalPrice: 25000, stock: 4, sku: "DB-HAMP-DLX" },
];

export const DEFAULT_PROMOTIONS = [
  {
    id: "pr1",
    code: "MANIS20",
    title: "Diskon 20% Pengguna Baru",
    description: "Dapatkan potongan 20% (maksimal Rp 25.000) untuk pesanan pertamamu!",
    discountType: "percentage",
    discountValue: 20,
    minPurchase: 50000,
    maxDiscount: 25000,
    quota: 200,
    usedCount: 0,
    bannerImageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    isBanner: 1,
    isActive: 1,
  },
  {
    id: "pr2",
    code: "DESSERT10K",
    title: "Potongan Rp 10.000 Weekend Treat",
    description: "Potongan langsung Rp 10.000 dengan minimal belanja Rp 75.000.",
    discountType: "fixed",
    discountValue: 10000,
    minPurchase: 75000,
    maxDiscount: 10000,
    quota: 100,
    usedCount: 0,
    bannerImageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1200&q=80",
    isBanner: 1,
    isActive: 1,
  },
  {
    id: "pr3",
    code: "ONGKIRHEMAT",
    title: "Gratis / Subsidi Ongkir Rp 15.000",
    description: "Subsidi ongkir kurir instan/sameday Rp 15.000 dengan minimal order Rp 90.000.",
    discountType: "fixed",
    discountValue: 15000,
    minPurchase: 90000,
    maxDiscount: 15000,
    quota: 150,
    usedCount: 0,
    bannerImageUrl: null,
    isBanner: 0,
    isActive: 1,
  },
];
